#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/output"
CONF_FILE="$SCRIPT_DIR/airgap.conf"
LEDGER_FILE="$SCRIPT_DIR/output/.ledger"

# --- load config ---
ENABLE_OPENCLAW=""
ENABLE_HERMES=""
if [[ -f "$CONF_FILE" ]]; then
  source "$CONF_FILE"
fi

# --- defaults ---
MODE=""
ARCH=""
OPENCLAW_VERSION=""
HERMES_IMAGE="${HERMES_IMAGE:-hermes-agent:latest}"
SAVE_ENGINE="${SAVE_ENGINE:-podman}"
LOAD_ENGINE="${LOAD_ENGINE:-docker}"

usage() {
  cat <<EOF
Usage: $(basename "$0") --save|--load [options]

Modes:
  --save       Build/save images and compress repo (connected machine, uses $SAVE_ENGINE)
  --load       Load images and patch setup (airgapped machine, uses $LOAD_ENGINE)

Options:
  --arch ARCH                Platform, e.g. linux/arm64 or linux/amd64
  --openclaw-version VER     OpenClaw version (optional for --save: auto-detects latest major release)
  --hermes-image IMAGE       Hermes image name (default: $HERMES_IMAGE)
  --force                    Re-export even if version already in ledger
  --reconfigure              Re-run component selection dialog

Config: $CONF_FILE
Ledger: $LEDGER_FILE (tracks exported version:arch to prevent duplicates)

Examples:
  # Auto-detect latest release:
  ./airgapped.sh --save --arch linux/arm64

  # Pin specific version:
  ./airgapped.sh --save --arch linux/arm64 --openclaw-version 2026.4.26
  ./airgapped.sh --load --arch linux/arm64 --openclaw-version 2026.4.26
EOF
  exit 1
}

# --- parse args ---
FORCE=false
RECONFIGURE=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --save) MODE="save"; shift ;;
    --load) MODE="load"; shift ;;
    --arch) ARCH="$2"; shift 2 ;;
    --openclaw-version) OPENCLAW_VERSION="$2"; shift 2 ;;
    --hermes-image) HERMES_IMAGE="$2"; shift 2 ;;
    --force) FORCE=true; shift ;;
    --reconfigure) RECONFIGURE=true; shift ;;
    -h|--help) usage ;;
    *) echo "ERROR: Unknown arg: $1" >&2; usage ;;
  esac
done

[[ -z "$MODE" ]] && { echo "ERROR: --save or --load required" >&2; usage; }
[[ -z "$ARCH" ]] && { echo "ERROR: --arch required (e.g. linux/arm64)" >&2; usage; }

# linux/arm64 -> arm64
ARCH_SUFFIX="${ARCH#*/}"

# --- validate architecture ---
VALID_ARCHS="amd64 arm64 arm s390x ppc64le riscv64"
if ! echo "$VALID_ARCHS" | grep -qw "$ARCH_SUFFIX"; then
  echo "ERROR: Invalid architecture '$ARCH_SUFFIX'" >&2
  echo "  Valid: $VALID_ARCHS" >&2
  echo "  Example: --arch linux/arm64" >&2
  exit 1
fi

# ============================================================
#  Auto-detect latest major release from GitHub
# ============================================================
fetch_latest_version() {
  local repo="${OPENCLAW_REPO:-https://github.com/openclaw/openclaw}"
  # extract owner/repo from URL
  local owner_repo
  owner_repo="$(echo "$repo" | sed 's|.*github\.com/||; s|\.git$||')"

  echo "==> Checking latest release from $owner_repo..." >&2

  local releases_json
  if ! releases_json="$(gh api "repos/$owner_repo/releases" \
    --jq '[.[] | select(.prerelease == false and (.tag_name | test("beta|alpha|rc") | not)) | .tag_name] | first' \
    2>/dev/null)"; then
    # fallback: try curl if gh is not available
    if ! releases_json="$(curl -sf "https://api.github.com/repos/$owner_repo/releases" \
      | python3 -c "
import sys, json
releases = json.load(sys.stdin)
for r in releases:
    tag = r['tag_name']
    if not r['prerelease'] and not any(x in tag for x in ['beta','alpha','rc']):
        print(tag)
        break
" 2>/dev/null)"; then
      echo "ERROR: Could not fetch releases from GitHub. Specify --openclaw-version manually." >&2
      exit 1
    fi
  fi

  # strip leading 'v' if present: v2026.4.26 -> 2026.4.26
  releases_json="${releases_json#v}"

  if [[ -z "$releases_json" ]]; then
    echo "ERROR: No stable release found. Specify --openclaw-version manually." >&2
    exit 1
  fi

  echo "$releases_json"
}

# auto-detect version for --save if not specified
if [[ -z "$OPENCLAW_VERSION" ]]; then
  if [[ "$MODE" == "save" ]]; then
    OPENCLAW_VERSION="$(fetch_latest_version)"
    echo "==> Latest major release: v$OPENCLAW_VERSION"
  else
    echo "ERROR: --openclaw-version required for --load (no internet on airgapped machine)" >&2
    usage
  fi
fi

# ============================================================
#  Interactive setup dialog
# ============================================================
ask_yes_no() {
  local prompt="$1"
  local default="${2:-}"
  local reply
  while true; do
    read -rp "$prompt " reply
    case "${reply,,}" in
      y|yes) echo "yes"; return ;;
      n|no)  echo "no"; return ;;
      "")
        if [[ -n "$default" ]]; then
          echo "$default"; return
        fi
        ;;
    esac
    echo "  Please answer yes or no."
  done
}

write_config() {
  cat > "$CONF_FILE" <<EOF
# airgap.conf - auto-generated by setup dialog
# Re-run with --reconfigure to change

# components
ENABLE_OPENCLAW="$ENABLE_OPENCLAW"
ENABLE_HERMES="$ENABLE_HERMES"

# openclaw
OPENCLAW_REPO="https://github.com/openclaw/openclaw"
OPENCLAW_BUILD_ARGS="--build-arg OPENCLAW_DOCKER_APT_PACKAGES= --build-arg OPENCLAW_EXTENSIONS= --build-arg OPENCLAW_INSTALL_DOCKER_CLI="

# hermes
HERMES_IMAGE="$HERMES_IMAGE"

# engine per side
SAVE_ENGINE="$SAVE_ENGINE"
LOAD_ENGINE="$LOAD_ENGINE"
EOF
}

ask_choice() {
  local prompt="$1"
  shift
  local options=("$@")
  local reply
  while true; do
    echo "$prompt"
    for i in "${!options[@]}"; do
      echo "  $((i+1))) ${options[$i]}"
    done
    read -rp "Choice [1-${#options[@]}]: " reply
    if [[ "$reply" =~ ^[0-9]+$ ]] && (( reply >= 1 && reply <= ${#options[@]} )); then
      echo "${options[$((reply-1))]}"
      return
    fi
    echo "  Invalid choice."
  done
}

run_setup_dialog() {
  echo ""
  echo "======================================"
  echo "  Airgapped Deployment - Setup"
  echo "======================================"
  echo ""

  ENABLE_HERMES="$(ask_yes_no "Enable Hermes Agent? [yes/no]:")"
  ENABLE_OPENCLAW="$(ask_yes_no "Enable OpenClaw? [yes/no]:")"

  if [[ "$ENABLE_HERMES" == "no" && "$ENABLE_OPENCLAW" == "no" ]]; then
    echo ""
    echo "  No components selected. Config not saved."
    echo "  You will be asked again on the next run."
    echo ""
    if [[ -f "$CONF_FILE" ]]; then
      sed -i '/^ENABLE_OPENCLAW=/d; /^ENABLE_HERMES=/d' "$CONF_FILE"
    fi
    exit 0
  fi

  echo ""
  echo "Container engine for building/saving (this machine):"
  SAVE_ENGINE="$(ask_choice "" "podman" "docker")"

  echo "Container engine for loading/deploying (airgapped machine):"
  LOAD_ENGINE="$(ask_choice "" "podman" "docker")"

  echo ""
  echo "  Hermes Agent:    $ENABLE_HERMES"
  echo "  OpenClaw:        $ENABLE_OPENCLAW"
  echo "  Build engine:    $SAVE_ENGINE"
  echo "  Deploy engine:   $LOAD_ENGINE"
  echo ""

  write_config
  echo "  Saved to $CONF_FILE"
  echo ""
}

# trigger dialog if: first run, both disabled, or --reconfigure
needs_setup() {
  [[ "$RECONFIGURE" == true ]] && return 0
  [[ -z "$ENABLE_OPENCLAW" && -z "$ENABLE_HERMES" ]] && return 0
  [[ "$ENABLE_OPENCLAW" == "no" && "$ENABLE_HERMES" == "no" ]] && return 0
  return 1
}

if needs_setup; then
  run_setup_dialog
fi

# ============================================================
#  QEMU cross-arch check
# ============================================================
check_qemu() {
  local host_arch
  host_arch="$(uname -m)"

  case "$host_arch" in
    x86_64)  host_arch="amd64" ;;
    aarch64) host_arch="arm64" ;;
  esac

  if [[ "$host_arch" == "$ARCH_SUFFIX" ]]; then
    return 0
  fi

  echo "==> Cross-architecture build: host=$host_arch, target=$ARCH_SUFFIX"

  local binfmt_dir="/proc/sys/fs/binfmt_misc"
  local qemu_registered=false

  if [[ -d "$binfmt_dir" ]]; then
    for entry in "$binfmt_dir"/qemu-*; do
      if [[ -f "$entry" ]] && grep -qi "$ARCH_SUFFIX\|aarch64\|arm" "$entry" 2>/dev/null; then
        qemu_registered=true
        break
      fi
    done
  fi

  if [[ "$qemu_registered" == true ]]; then
    echo "    QEMU binfmt registered for $ARCH_SUFFIX"
    return 0
  fi

  echo ""
  echo "ERROR: QEMU user-space emulation not available for $ARCH_SUFFIX" >&2
  echo "" >&2
  echo "  Cross-architecture builds need qemu-user-static. Install it (requires root):" >&2
  echo "" >&2
  echo "  Option A - system package:" >&2
  echo "    sudo apt install qemu-user-static" >&2
  echo "    sudo systemctl restart systemd-binfmt" >&2
  echo "" >&2
  echo "  Option B - via container:" >&2
  echo "    sudo podman run --privileged --rm tonistiigi/binfmt --install $ARCH_SUFFIX" >&2
  echo "" >&2
  exit 1
}

# file names
OPENCLAW_IMAGE_FILE="openclaw_${ARCH_SUFFIX}_v${OPENCLAW_VERSION}.tar.gz"
OPENCLAW_REPO_FILE="openclaw_github_v${OPENCLAW_VERSION}.tar.gz"
HERMES_IMAGE_FILE="hermes_${ARCH_SUFFIX}_v${OPENCLAW_VERSION}.tar.gz"

# --- ledger: duplicate prevention ---
ledger_contains() {
  local entry="$1"
  [[ -f "$LEDGER_FILE" ]] && grep -qxF "$entry" "$LEDGER_FILE"
}

ledger_add() {
  local entry="$1"
  mkdir -p "$(dirname "$LEDGER_FILE")"
  echo "$entry" >> "$LEDGER_FILE"
}

# ============================================================
#  --save: connected machine (podman)
# ============================================================
do_save() {
  check_qemu

  # --- check if anything needs updating ---
  local oc_ledger="openclaw:${OPENCLAW_VERSION}:${ARCH_SUFFIX}"
  local hermes_ledger="hermes:${OPENCLAW_VERSION}:${ARCH_SUFFIX}"
  local needs_work=false

  if [[ "$ENABLE_OPENCLAW" == "yes" ]] && ! ledger_contains "$oc_ledger"; then
    needs_work=true
  fi
  if [[ "$ENABLE_HERMES" == "yes" ]] && ! ledger_contains "$hermes_ledger"; then
    needs_work=true
  fi

  if [[ "$FORCE" != true && "$needs_work" == false ]]; then
    echo ""
    echo "==> System is up to date (v$OPENCLAW_VERSION / $ARCH_SUFFIX)"
    echo "    No update needed. Use --force to re-export."
    echo ""
    return 0
  fi

  mkdir -p "$OUTPUT_DIR"

  # --- openclaw ---
  if [[ "$ENABLE_OPENCLAW" == "yes" ]]; then
    if [[ "$FORCE" != true ]] && ledger_contains "$oc_ledger"; then
      echo "==> OpenClaw v$OPENCLAW_VERSION already exported, skipping"
    else
      # clone repo — remove old version first to save space
      if [[ -d "$SCRIPT_DIR/openclaw" ]]; then
        local existing_tag=""
        existing_tag="$(git -C "$SCRIPT_DIR/openclaw" describe --tags --exact-match 2>/dev/null || true)"
        existing_tag="${existing_tag#v}"
        if [[ "$existing_tag" == "$OPENCLAW_VERSION" ]]; then
          echo "==> Repo already at v${OPENCLAW_VERSION}, reusing"
        else
          echo "==> Removing old repo (${existing_tag:-unknown}) to save space"
          rm -rf "$SCRIPT_DIR/openclaw"
        fi
      fi
      if [[ ! -d "$SCRIPT_DIR/openclaw" ]]; then
        echo "==> Cloning openclaw repo v${OPENCLAW_VERSION} (shallow)..."
        git clone --depth 1 --branch "v${OPENCLAW_VERSION}" \
          "${OPENCLAW_REPO:-https://github.com/openclaw/openclaw}" "$SCRIPT_DIR/openclaw"
      fi

      # build image from inside the repo dir
      local oc_image="openclaw:local"
      echo "==> Building openclaw image: $oc_image (platform $ARCH)"
      echo "    Cached layers are reused - only deltas are pulled"
      (
        cd "$SCRIPT_DIR/openclaw"
        $SAVE_ENGINE build \
          --progress=plain \
          --platform "$ARCH" \
          ${OPENCLAW_BUILD_ARGS:-} \
          -t "$oc_image" \
          -f Dockerfile \
          .
      )

      # save image
      echo "==> Saving openclaw image -> $OPENCLAW_IMAGE_FILE"
      $SAVE_ENGINE save "$oc_image" | gzip > "$OUTPUT_DIR/$OPENCLAW_IMAGE_FILE"

      # compress repo
      echo "==> Compressing repo -> $OPENCLAW_REPO_FILE"
      tar -czf "$OUTPUT_DIR/$OPENCLAW_REPO_FILE" -C "$SCRIPT_DIR" openclaw/

      ledger_add "$oc_ledger"
    fi
  else
    echo "==> OpenClaw: disabled, skipping"
  fi

  # --- hermes ---
  if [[ "$ENABLE_HERMES" == "yes" ]]; then
    if [[ "$FORCE" != true ]] && ledger_contains "$hermes_ledger"; then
      echo "==> Hermes v$OPENCLAW_VERSION already exported, skipping"
    else
      if $SAVE_ENGINE image inspect "$HERMES_IMAGE" >/dev/null 2>&1; then
        echo "==> Saving hermes image ($HERMES_IMAGE) -> $HERMES_IMAGE_FILE"
        $SAVE_ENGINE save "$HERMES_IMAGE" | gzip > "$OUTPUT_DIR/$HERMES_IMAGE_FILE"
        ledger_add "$hermes_ledger"
      else
        echo "WARNING: Hermes image '$HERMES_IMAGE' not found locally."
        echo "  Build it first: $SAVE_ENGINE build --platform $ARCH -t $HERMES_IMAGE <hermes-repo-path>"
      fi
    fi
  else
    echo "==> Hermes Agent: disabled, skipping"
  fi

  echo ""
  echo "==> Done. Output files:"
  ls -lh "$OUTPUT_DIR/"*.tar.gz 2>/dev/null || echo "  (none)"
  echo ""
  echo "Transfer files to the airgapped machine, then run:"
  echo "  ./airgapped.sh --load --arch $ARCH --openclaw-version $OPENCLAW_VERSION"
}

# ============================================================
#  --load: airgapped machine (docker)
# ============================================================
do_load() {
  find_file() {
    local pattern="$1"
    local found=""
    for dir in "$OUTPUT_DIR" "$PWD" "$SCRIPT_DIR"; do
      found="$(compgen -G "$dir/$pattern" 2>/dev/null | head -1)" && break
    done
    echo "$found"
  }

  # --- openclaw ---
  if [[ "$ENABLE_OPENCLAW" == "yes" ]]; then
    local oc_image_tar oc_repo_tar
    oc_image_tar="$(find_file "$OPENCLAW_IMAGE_FILE")"
    oc_repo_tar="$(find_file "$OPENCLAW_REPO_FILE")"

    # load image
    if $LOAD_ENGINE image inspect "openclaw:local" >/dev/null 2>&1; then
      echo "==> openclaw:local already loaded, skipping"
    elif [[ -n "$oc_image_tar" && -f "$oc_image_tar" ]]; then
      echo "==> Loading openclaw image from $oc_image_tar"
      gunzip -c "$oc_image_tar" | $LOAD_ENGINE load
    else
      echo "ERROR: OpenClaw image tar not found and openclaw:local not present" >&2
      echo "  Expected: $OPENCLAW_IMAGE_FILE" >&2
      exit 1
    fi

    # extract repo
    if [[ ! -d "$SCRIPT_DIR/openclaw" ]]; then
      if [[ -n "$oc_repo_tar" && -f "$oc_repo_tar" ]]; then
        echo "==> Extracting repo from $oc_repo_tar"
        tar -xzf "$oc_repo_tar" -C "$SCRIPT_DIR"
      else
        echo "ERROR: No repo tar and no openclaw/ directory" >&2
        exit 1
      fi
    else
      echo "==> Repo directory exists at $SCRIPT_DIR/openclaw"
    fi

    # patch setup.sh
    patch_setup
  else
    echo "==> OpenClaw: disabled, skipping"
  fi

  # --- hermes ---
  if [[ "$ENABLE_HERMES" == "yes" ]]; then
    local hermes_tar
    hermes_tar="$(find_file "hermes_${ARCH_SUFFIX}_*.tar.gz")"

    if $LOAD_ENGINE image inspect "$HERMES_IMAGE" >/dev/null 2>&1; then
      echo "==> Hermes image already loaded, skipping"
    elif [[ -n "$hermes_tar" && -f "$hermes_tar" ]]; then
      echo "==> Loading hermes image from $hermes_tar"
      gunzip -c "$hermes_tar" | $LOAD_ENGINE load
    else
      echo "WARNING: No hermes image tar found, skipping"
    fi
  else
    echo "==> Hermes Agent: disabled, skipping"
  fi

  echo ""
  echo "==> Images loaded:"
  $LOAD_ENGINE images | grep -E "(openclaw|hermes)" || true

  if [[ "$ENABLE_OPENCLAW" == "yes" ]]; then
    echo ""
    echo "==> Deploy openclaw:"
    echo "  cd $SCRIPT_DIR/openclaw"
    echo "  OPENCLAW_IMAGE=openclaw:local bash scripts/docker/setup.sh"
  fi
}

# ============================================================
#  Patch setup.sh for airgapped deployment
# ============================================================
patch_setup() {
  local setup_file="$SCRIPT_DIR/openclaw/scripts/docker/setup.sh"
  local patch_file="$SCRIPT_DIR/patches/openclaw-setup-airgap.patch"

  if [[ ! -f "$setup_file" ]]; then
    echo "ERROR: setup.sh not found at $setup_file" >&2
    exit 1
  fi

  if [[ ! -f "$patch_file" ]]; then
    echo "ERROR: Patch file not found at $patch_file" >&2
    exit 1
  fi

  if grep -q 'already exists locally, skipping' "$setup_file" 2>/dev/null; then
    echo "==> setup.sh already patched"
    return
  fi

  echo "==> Patching setup.sh with $patch_file"
  cp "$setup_file" "${setup_file}.bak"

  if ! patch --forward --directory="$SCRIPT_DIR/openclaw" -p1 < "$patch_file"; then
    echo "ERROR: Patch failed. setup.sh may have changed upstream." >&2
    echo "  Backup at: ${setup_file}.bak" >&2
    echo "  Patch file: $patch_file" >&2
    cp "${setup_file}.bak" "$setup_file"
    exit 1
  fi

  echo "  Patched successfully"
}

# ============================================================
#  Main
# ============================================================
case "$MODE" in
  save) do_save ;;
  load) do_load ;;
esac
